# Generated by Django 5.2.7 on 2025-10-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_account_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '계좌', 'verbose_name_plural': '계좌'},
        ),
    ]
