# Generated by Django 5.2.7 on 2025-10-14 02:07

import apps.users.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(db_column='nickname', max_length=50, verbose_name='닉네임')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='이름')),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=20, validators=[django.core.validators.RegexValidator(message='전화번호는 - 포함한 최대 20자리 숫자 형식이어야합니다.', regex='^\\-?1?\\d{1,20}$')], verbose_name='전화번호')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True, verbose_name='마지막 로그인')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=django.utils.timezone.now, verbose_name='스태프 여부')),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False, verbose_name='관리자 플래그')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['nickname'], name='users_nicknam_172a64_idx'), models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx')],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
