# Generated by Django 5.2.7 on 2025-10-14 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 금액')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 후 잔액')),
                ('description', models.CharField(max_length=255, verbose_name='거래 내역 설명')),
                ('transaction_direction', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금')], max_length=20, verbose_name='입출금 타입')),
                ('transaction_type', models.CharField(choices=[('ATM', 'ATM 거래'), ('TRANSFER', '계좌이체'), ('AUTOMATIC_TRANSFER', '자동이체'), ('CARD', '카드결제'), ('INTEREST', '이자')], max_length=30, verbose_name='거래 타입')),
                ('transaction_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='거래 일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to='accounts.accounts', verbose_name='계좌 정보')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역 목록',
                'db_table': 'transaction_history',
            },
        ),
    ]
